name: .NET CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: Lab6.sln        
      Test_Project_Path: TestProject/TestProject.csproj 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0 

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build the project
      run: dotnet build ${{ env.Solution_Name }} --configuration Release

    - name: Run unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --verbosity normal
